### ISSUE TITLE
Broken Colab link

### ISSUE THREAD

**Issue by byarbrough** [USAFA-ECE/ece382#1]
Due to the repo migration, the "Open in Colab" button is broken in [Lab 16](https://usafa-ece.github.io/ece382/Assignments/lab16.html?highlight=Colab#graph-duty-cycle-versus-actual-speed)

One approach is to add the following to `_config.yml` to add a button to automatically open jupyter notebooks in colab
```yaml
# Add a "Launch on Google Colab" button to .ipynb files
launch_buttons:
  colab_url: "https://colab.research.google.com"
```
